name: DevSecOps CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  security:
    name: CI/CD + Security Scans
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t fin-bank-api .

    - name: Run Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: fin-bank-api
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH

    - name: Run Snyk Scan
      uses: snyk/actions@master
      with:
        command: test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
