name: CI - Build & Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker Image
      run: docker build -t finbank-api .

    - name: Install Trivy
      run: |
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.49.1_Linux-64bit.deb

    - name: Trivy Scan - Docker Image
      run: trivy image --severity HIGH,CRITICAL --exit-code 0 --format table finbank-api

    - name: Trivy Scan - Python Dependencies
      run: trivy fs --scanners vuln --severity HIGH,CRITICAL --exit-code 0 --format table .
